// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transactionpb.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	transactionpb.proto

It has these top-level messages:
	TransactionPb
	TransactionPbTmp
*/
package job

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TransactionPb struct {
	From     []byte   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To       string   `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	Method   string   `protobuf:"bytes,3,opt,name=method" json:"method,omitempty"`
	Args     []string `protobuf:"bytes,4,rep,name=args" json:"args,omitempty"`
	Bytecode []byte   `protobuf:"bytes,5,opt,name=bytecode,proto3" json:"bytecode,omitempty"`
	Nonce    int64    `protobuf:"varint,6,opt,name=nonce" json:"nonce,omitempty"`
	V        []byte   `protobuf:"bytes,7,opt,name=v,proto3" json:"v,omitempty"`
	R        []byte   `protobuf:"bytes,8,opt,name=r,proto3" json:"r,omitempty"`
	S        []byte   `protobuf:"bytes,9,opt,name=s,proto3" json:"s,omitempty"`
	Hash     []byte   `protobuf:"bytes,10,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *TransactionPb) Reset()                    { *m = TransactionPb{} }
func (m *TransactionPb) String() string            { return proto.CompactTextString(m) }
func (*TransactionPb) ProtoMessage()               {}
func (*TransactionPb) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TransactionPb) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *TransactionPb) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TransactionPb) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *TransactionPb) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *TransactionPb) GetBytecode() []byte {
	if m != nil {
		return m.Bytecode
	}
	return nil
}

func (m *TransactionPb) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *TransactionPb) GetV() []byte {
	if m != nil {
		return m.V
	}
	return nil
}

func (m *TransactionPb) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *TransactionPb) GetS() []byte {
	if m != nil {
		return m.S
	}
	return nil
}

func (m *TransactionPb) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type TransactionPbTmp struct {
	From     []byte   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To       string   `protobuf:"bytes,2,opt,name=to" json:"to,omitempty"`
	Method   string   `protobuf:"bytes,3,opt,name=method" json:"method,omitempty"`
	Args     []string `protobuf:"bytes,4,rep,name=args" json:"args,omitempty"`
	Bytecode []byte   `protobuf:"bytes,5,opt,name=bytecode,proto3" json:"bytecode,omitempty"`
	Nonce    int64    `protobuf:"varint,6,opt,name=nonce" json:"nonce,omitempty"`
}

func (m *TransactionPbTmp) Reset()                    { *m = TransactionPbTmp{} }
func (m *TransactionPbTmp) String() string            { return proto.CompactTextString(m) }
func (*TransactionPbTmp) ProtoMessage()               {}
func (*TransactionPbTmp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TransactionPbTmp) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *TransactionPbTmp) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TransactionPbTmp) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *TransactionPbTmp) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *TransactionPbTmp) GetBytecode() []byte {
	if m != nil {
		return m.Bytecode
	}
	return nil
}

func (m *TransactionPbTmp) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func init() {
	proto.RegisterType((*TransactionPb)(nil), "types.TransactionPb")
	proto.RegisterType((*TransactionPbTmp)(nil), "types.TransactionPbTmp")
}

func init() { proto.RegisterFile("transactionpb.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x90, 0x4d, 0x4a, 0xc4, 0x40,
	0x10, 0x85, 0xa9, 0x64, 0x12, 0x27, 0xc5, 0x28, 0x52, 0x8a, 0x14, 0xae, 0xc2, 0xac, 0xb2, 0x72,
	0xe3, 0x45, 0x24, 0xcc, 0x05, 0xd2, 0x99, 0xd6, 0xb8, 0x48, 0x57, 0xd3, 0x5d, 0x0c, 0xe4, 0x1e,
	0xde, 0xcb, 0x2b, 0x49, 0x77, 0x8b, 0xe2, 0x09, 0xdc, 0xbd, 0xaf, 0xfe, 0x5f, 0xe1, 0x9d, 0x86,
	0xc9, 0xc5, 0x69, 0xd6, 0x77, 0x71, 0xde, 0x3c, 0xf9, 0x20, 0x2a, 0xd4, 0xe8, 0xe6, 0x6d, 0x3c,
	0x7e, 0x02, 0x5e, 0x9f, 0x7e, 0xd3, 0x2f, 0x86, 0x08, 0x77, 0xaf, 0x41, 0x56, 0x86, 0x1e, 0x86,
	0xc3, 0x98, 0x35, 0xdd, 0x60, 0xa5, 0xc2, 0x55, 0x0f, 0x43, 0x37, 0x56, 0x2a, 0xf4, 0x80, 0xed,
	0x6a, 0x75, 0x91, 0x33, 0xd7, 0x39, 0xf6, 0x4d, 0xa9, 0x77, 0x0a, 0x6f, 0x91, 0x77, 0x7d, 0x3d,
	0x74, 0x63, 0xd6, 0xf4, 0x88, 0x7b, 0xb3, 0xa9, 0x9d, 0xe5, 0x6c, 0xb9, 0xc9, 0x33, 0x7f, 0x98,
	0xee, 0xb1, 0x71, 0xe2, 0x66, 0xcb, 0x6d, 0x0f, 0x43, 0x3d, 0x16, 0xa0, 0x03, 0xc2, 0x85, 0xaf,
	0x72, 0x29, 0x5c, 0x12, 0x05, 0xde, 0x17, 0x0a, 0x89, 0x22, 0x77, 0x85, 0x62, 0xda, 0xb7, 0x4c,
	0x71, 0x61, 0x2c, 0xb7, 0x26, 0x7d, 0xfc, 0x00, 0xbc, 0xfd, 0xe3, 0xe8, 0xb4, 0xfa, 0xff, 0x37,
	0x65, 0xda, 0xfc, 0xf6, 0xe7, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcf, 0xe8, 0xae, 0xde, 0x8d,
	0x01, 0x00, 0x00,
}
